version: '3.8'
services:
  postgres-booking:
    image: postgres:latest
    container_name: bookingcore-db
    environment:
      POSTGRES_USER: sanmartinomar
      POSTGRES_PASSWORD: sanmartinomar
      POSTGRES_DB: bookingcore_db
    ports:
      - "5433:5432" # Cambia el puerto externo para evitar conflictos
    networks:
      - authcore-network
    volumes:
      - C:/Postgres/bookingcore:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    depends_on:
      - postgres
      - postgres-booking
    networks:
      - authcore-network

networks:
  authcore-network:
    driver: bridge
